name: ci

on: [push, pull_request]

jobs:

  build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        deno_version: ['v0.37.0']

    steps:
    - name: Configure git
      run: git config --global core.symlinks true

    - name: Clone repository
      uses: actions/checkout@v2

    - name: Configure environment variable's
      run: |
        echo "::set-env name=DENO_INSTALL::$HOME/.local"
        echo "::add-path::$HOME/.local/bin"

    - name: Install deno ${{ matrix.deno_version }}
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s ${{ matrix.deno_version }}
        deno -h

    - name: Run test's
      run: deno test --allow-env
