name: ci

on: [push, pull_request]

jobs:

  build:
    name: Test on ${{ matrix.os }} with deno-${{ matrix.deno_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        deno_version: [ 'v1.0.0', 'v1.1.0', 'v1.1.1' ]

    steps:
      - name: Configure git
        run: git config --global core.symlinks true

      - name: Clone repository
        uses: actions/checkout@master

      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno_version }}

      - name: Deno Version
        run: deno -V

      - name: Run command test's
        run: deno test packages/command/test/command --unstable --allow-env && deno test packages/command/test/option && deno test packages/command/test/type

      - name: Run flags test's
        run: deno test packages/flags

      - name: Run keycode test's
        run: deno test packages/keycode

      - name: Run prompt test's
        run: deno test packages/prompt --unstable

      - name: Run table test's
        run: deno test packages/table
